#! /bin/sh

# check correct usage
if test $# -lt 1;
then
  echo Usage: $0 plot.xml
  exit
fi 

f=$1
dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd) || exit 1

"$dir/xslttransform" "$f" "$dir/@ALPS_XML_FROM_BINDIR@/plot2gp.xsl"
