#! /bin/bash -f

# check correct usage
if test $# -lt 2;
then
  echo Usage: $0 plot.xml archive.xml 
  echo or     $0 plot.xml task1.xml task2.xml ...
  exit
fi 

# check if PALM_DIR is set
if test x$PALM_DIR = x; then
  echo Please set the PALM_DIR environment variable to specify the palm directory
  exit
fi

bindir=$PALM_DIR/bin
xsldir=$PALM_DIR/lib/xml

# define xsl-settings from xml-plot input  
$bindir/xslttransform $1 $xsldir/plot2xsl.xsl > $xsldir/plotsettings.xsl 

# generate xml-plot output from archive or list of task files
if test $# -gt 2;
then
  $bindir/archivecat `echo ${*:1} | cut -d' ' -f2-` > /tmp/archive$$
  $bindir/xslttransform /tmp/archive$$ $xsldir/archive2plot.xsl > /tmp/plot$$
  rm /tmp/archive$$
else
  xslttransform $2 $xsldir/archive2plot.xsl > /tmp/plot$$  
fi
# rm $xsldir/plotsettings.xsl

# generate text output from previously generated xml-plot
xslttransform /tmp/plot$$ $xsldir/plot2text.xsl 
rm /tmp/plot$$
