#! /bin/bash -f

# check correct usage
if test $# -lt 2;
then
  echo Usage: $0 plot.xml archive.xml 
  echo or     $0 plot.xml task1.xml task2.xml ...
  exit
fi 

# check if PALM_DIR is set
if test x$PALM_DIR = x; then
  echo Please set the PALM_DIR environment variable to specify the palm directory
  exit
fi
 
dir=$PALM_DIR/tools

# define xsl-settings from xml-plot input  
xslttransform $1 $dir/plot2xsl.xsl > $dir/plotsettings.xsl 

# generate xml-plot output from archive or list of task files
if test $# -gt 2;
then
  archivecat `echo ${*:1} | cut -d' ' -f2-` > /tmp/archive$$
  xslttransform /tmp/archive$$ $dir/archive2plot.xsl > /tmp/plot$$
  rm /tmp/archive$$
else
  xslttransform $2 $dir/archive2plot.xsl > /tmp/plot$$  
fi
rm $dir/plotsettings.xsl

# generate text output from previously generated xml-plot
xslttransform /tmp/plot$$ $dir/plot2html.xsl 
rm /tmp/plot$$
