#  Copyright Michele Dolfi 2012.
#  Distributed under the Boost Software License, Version 1.0.
#      (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)

# Setting additional information in the CTest build name:
# - NGS enabled?
# - System Boost or path to sources?
# - Version of boost


# Default behavior of CTest.cmake
IF(NOT BUILDNAME)
  SET(DART_COMPILER "${CMAKE_CXX_COMPILER}")
  IF(NOT DART_COMPILER)
    SET(DART_COMPILER "${CMAKE_C_COMPILER}")
  ENDIF(NOT DART_COMPILER)
  IF(NOT DART_COMPILER)
    SET(DART_COMPILER "unknown")
  ENDIF(NOT DART_COMPILER)
  IF(WIN32)
    SET(DART_NAME_COMPONENT "NAME_WE")
  ELSE(WIN32)
    SET(DART_NAME_COMPONENT "NAME")
  ENDIF(WIN32)
### ALPS ADDITION
  if(ALPS_SYSTEM_NAME)
    set(BUILD_NAME_SYSTEM_NAME "${ALPS_SYSTEM_NAME}")
  endif(ALPS_SYSTEM_NAME)
### END ADDITION
  IF(NOT BUILD_NAME_SYSTEM_NAME)
    SET(BUILD_NAME_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}")
  ENDIF(NOT BUILD_NAME_SYSTEM_NAME)
  IF(WIN32)
    SET(BUILD_NAME_SYSTEM_NAME "Win32")
  ENDIF(WIN32)
  IF(UNIX OR BORLAND)
    GET_FILENAME_COMPONENT(DART_CXX_NAME 
      "${CMAKE_CXX_COMPILER}" ${DART_NAME_COMPONENT})
  ELSE(UNIX OR BORLAND)
    GET_FILENAME_COMPONENT(DART_CXX_NAME 
      "${CMAKE_BUILD_TOOL}" ${DART_NAME_COMPONENT})
  ENDIF(UNIX OR BORLAND)
  IF(DART_CXX_NAME MATCHES "msdev")
    SET(DART_CXX_NAME "vs60")
  ENDIF(DART_CXX_NAME MATCHES "msdev")
  IF(DART_CXX_NAME MATCHES "devenv")
    GET_VS_VERSION_STRING("${CMAKE_GENERATOR}" DART_CXX_NAME)
  ENDIF(DART_CXX_NAME MATCHES "devenv")
  SET(BUILDNAME "${BUILD_NAME_SYSTEM_NAME}-${DART_CXX_NAME}")
ENDIF(NOT BUILDNAME)


# Add Boost settings
if(Boost_ROOT_DIR)
  set(BUILDNAME "${BUILDNAME} - Boost Src")
else()
  set(BUILDNAME "${BUILDNAME} - Boost System")
endif(Boost_ROOT_DIR)

set(BUILDNAME "${BUILDNAME} v${Boost_MAJOR_VERSION}_${Boost_MINOR_VERSION}_${Boost_SUBMINOR_VERSION}")


# Add NGS settings
if(ALPS_BUILD_NGS)
 set(BUILDNAME "${BUILDNAME} - NGS enabled")
else(ALPS_BUILD_NGS)
  set(BUILDNAME "${BUILDNAME} - NGS disabled")
endif(ALPS_BUILD_NGS)
