#! /bin/sh

date=`date +'%Y%m%d'`

case "x$1" in
  xboost | xboost-snapshot)
    module="boost"
    ;;
  xboost-sandbox | xboost-sandbox-snapshot)
    module="boost-sandbox"
    ;;
  xboost-bindings | xboost-bindings-snapshot)
    module="boost-sandbox"
    ;;
  *)
    echo "unknown module name"
    exit -1
esac
   
set -x

rm -rf $module
cvs -z3 -q -d :pserver:anonymous@cvs.boost.sourceforge.net:/cvsroot/$module export -r HEAD $module

if test -d "$module"; then
  chmod -R u+w $module
  mv $module $module-$date
  tar zcf $module-$date.tar.gz $module-$date

  if test "$module" = boost-sandbox; then
    rm -rf boost-bindings-$date
    mv $module-$date boost-bindings-$date
    rm -rf boost-bindings-$date/[J,L,c,t]* boost-bindings-$date/boost-build.jam boost-bindings-$date/boost.css
    rm -rf boost-bindings-$date/boost/[a-m,o-z]* boost-bindings-$date/boost/named*
    rm -rf boost-bindings-$date/libs/[a-m,o-z]* boost-bindings-$date/libs/named*
    tar zcf boost-bindings-$date.tar.gz boost-bindings-$date
    rm -rf boost-bindings-$date
  else
    rm -rf $module-$date
  fi
fi
