#  Copyright Matthias Troyer 2009 - 2010.
#  Distributed under the Boost Software License, Version 1.0.
#      (See accompanying file LICENSE_1_0.txt or copy at
#          http://www.boost.org/LICENSE_1_0.txt)


include /opt/alps/share/alps/include.mk

ising: ising-skeleton.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $(OBJ_golden) $(LDFLAGS) $(LIBS)
