# Keep Makefile consumers working while the SDK moves to exported CMake targets.
# The historical include.mk variable names and template are retained.
block()
  set(bindir "${CMAKE_INSTALL_FULL_BINDIR}")
  set(libdir "${CMAKE_INSTALL_FULL_LIBDIR}")
  set(CMAKE_C_COMPILER_ENV_VAR CC)
  set(CMAKE_CXX_COMPILER_ENV_VAR CXX)
  set(BASE_CPPFLAGS "-std=c++17")
  set(BASE_LIBS "${CMAKE_THREAD_LIBS_INIT}")
  # Put consumers before their providers for static archives and --as-needed.
  set(legacy_runtime_targets ${ALPS_SDK_RUNTIME_TARGETS})
  list(REMOVE_ITEM legacy_runtime_targets ALPS::alps)
  list(REVERSE legacy_runtime_targets)
  list(PREPEND legacy_runtime_targets ALPS::alps)
  foreach(runtime IN LISTS legacy_runtime_targets)
    get_target_property(name ${runtime} OUTPUT_NAME)
    if(NOT name)
      string(REPLACE "ALPS::" "alps_" name "${runtime}")
      if(runtime STREQUAL "ALPS::alps")
        set(name alps)
      endif()
    endif()
    string(APPEND BASE_LIBS " -l${name}")
  endforeach()
  set(Boost_INCLUDE_DIR_CONFIG "${Boost_INCLUDE_DIRS}")
  set(Boost_LIBS "")
  set(boost_runtime_directories "")
  set(boost_link_targets "")
  foreach(component IN LISTS ALPS_BOOST_COMPONENTS)
    list(APPEND boost_link_targets Boost::${component})
  endforeach()
  set(processed_boost_targets "")
  while(boost_link_targets)
    list(POP_FRONT boost_link_targets boost_target)
    if(NOT TARGET "${boost_target}" OR boost_target IN_LIST processed_boost_targets)
      continue()
    endif()
    list(APPEND processed_boost_targets "${boost_target}")
    # Some providers expose components such as regex as header-only targets.
    # Those have no linker file to add to the historical Makefile interface.
    get_target_property(component_type "${boost_target}" TYPE)
    if(NOT component_type STREQUAL "INTERFACE_LIBRARY")
      string(APPEND Boost_LIBS " $<TARGET_LINKER_FILE:${boost_target}>")
      list(APPEND boost_runtime_directories "$<TARGET_FILE_DIR:${boost_target}>")
    endif()
    # Make does not expand CMake target dependencies. Include the provider's
    # Boost dependencies too (for example filesystem -> atomic), so an ELF
    # executable can load them using its own RUNPATH.
    get_target_property(boost_interface "${boost_target}" INTERFACE_LINK_LIBRARIES)
    if(boost_interface)
      string(REGEX MATCHALL "Boost::[A-Za-z0-9_]+" boost_dependencies "${boost_interface}")
      list(APPEND boost_link_targets ${boost_dependencies})
    endif()
  endwhile()
  set(Boost_LDFLAGS "")
  if(boost_runtime_directories)
    # Absolute linker files do not tell ELF/dyld where to load their SONAMEs.
    # Preserve the provider paths, including configuration-specific locations.
    set(Boost_LDFLAGS "-Wl,-rpath,$<JOIN:$<REMOVE_DUPLICATES:${boost_runtime_directories}>, -Wl,-rpath,>")
  endif()
  list(GET HDF5_INCLUDE_DIRS 0 HDF5_INCLUDE_DIR)
  string(JOIN " " HDF5_LIBS ${HDF5_LIBRARIES})
  set(LAPACK_LIBS "")
  foreach(library IN LISTS LAPACK_LIBRARIES BLAS_LIBRARIES)
    # CMake accepts bare library names (as returned by Alpine's provider),
    # whereas the Makefile invokes the compiler driver directly.
    if(library MATCHES "^(.*)/([^/]+)\\.framework$")
      # CMake also accepts framework directories; a compiler driver needs
      # the corresponding framework search directory and name instead.
      string(APPEND LAPACK_LIBS " -F\"${CMAKE_MATCH_1}\" -framework \"${CMAKE_MATCH_2}\"")
    elseif(IS_ABSOLUTE "${library}" OR library MATCHES "^-")
      string(APPEND LAPACK_LIBS " ${library}")
    else()
      string(APPEND LAPACK_LIBS " -l${library}")
    endif()
  endforeach()
  if(ALPS_ENABLE_MPI)
    string(JOIN " " MPI_LIBS ${MPI_CXX_LIBRARIES})
    set(MPIEXEC "${MPIEXEC_EXECUTABLE}")
    set(MPI_INCLUDE_DIR_FIXED "")
    foreach(directory IN LISTS MPI_CXX_INCLUDE_DIRS)
      string(APPEND MPI_INCLUDE_DIR_FIXED " -I${directory}")
    endforeach()
  endif()
  configure_file("${PROJECT_SOURCE_DIR}/cmake/include.mk.in"
                 "${PROJECT_BINARY_DIR}/include.mk.in" @ONLY)
  file(GENERATE OUTPUT "${PROJECT_BINARY_DIR}/legacy/$<CONFIG>/include.mk"
    INPUT "${PROJECT_BINARY_DIR}/include.mk.in")
  install(FILES "${PROJECT_BINARY_DIR}/legacy/$<CONFIG>/include.mk"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/alps COMPONENT build)
endblock()
