# Keep Makefile consumers working while the SDK moves to exported CMake targets.
# The historical include.mk variable names and template are retained.
block()
  set(bindir "${CMAKE_INSTALL_FULL_BINDIR}")
  set(libdir "${CMAKE_INSTALL_FULL_LIBDIR}")
  set(CMAKE_C_COMPILER_ENV_VAR CC)
  set(CMAKE_CXX_COMPILER_ENV_VAR CXX)
  set(BASE_CPPFLAGS "-std=c++17")
  set(BASE_LIBS "${CMAKE_THREAD_LIBS_INIT}")
  foreach(runtime IN LISTS ALPS_SDK_RUNTIME_TARGETS)
    get_target_property(name ${runtime} OUTPUT_NAME)
    if(NOT name)
      string(REPLACE "ALPS::" "alps_" name "${runtime}")
      if(runtime STREQUAL "ALPS::alps")
        set(name alps)
      endif()
    endif()
    string(APPEND BASE_LIBS " -l${name}")
  endforeach()
  set(Boost_INCLUDE_DIR_CONFIG "${Boost_INCLUDE_DIRS}")
  set(Boost_LIBS "")
  foreach(component IN LISTS ALPS_BOOST_COMPONENTS)
    string(APPEND Boost_LIBS " $<TARGET_LINKER_FILE:Boost::${component}>")
  endforeach()
  list(GET HDF5_INCLUDE_DIRS 0 HDF5_INCLUDE_DIR)
  string(JOIN " " HDF5_LIBS ${HDF5_LIBRARIES})
  string(JOIN " " LAPACK_LIBS ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES})
  if(ALPS_ENABLE_MPI)
    string(JOIN " " MPI_LIBS ${MPI_CXX_LIBRARIES})
    set(MPIEXEC "${MPIEXEC_EXECUTABLE}")
    set(MPI_INCLUDE_DIR_FIXED "")
    foreach(directory IN LISTS MPI_CXX_INCLUDE_DIRS)
      string(APPEND MPI_INCLUDE_DIR_FIXED " -I${directory}")
    endforeach()
  endif()
  configure_file("${PROJECT_SOURCE_DIR}/cmake/include.mk.in"
                 "${PROJECT_BINARY_DIR}/include.mk.in" @ONLY)
  file(GENERATE OUTPUT "${PROJECT_BINARY_DIR}/legacy/$<CONFIG>/include.mk"
    INPUT "${PROJECT_BINARY_DIR}/include.mk.in")
  install(FILES "${PROJECT_BINARY_DIR}/legacy/$<CONFIG>/include.mk"
    DESTINATION ${CMAKE_INSTALL_DATADIR}/alps COMPONENT build)
endblock()
