# Copyright (C) 2026 ALPS collaboration. SPDX-License-Identifier: MIT
# SDK headers plus exact runtime files recorded by wheel packaging.
include_guard(GLOBAL)

function(alps_target_link_pyalps target)
  cmake_parse_arguments(PYALPS "" "PYTHON_EXECUTABLE" "" ${ARGN})
  if(NOT TARGET "${target}")
    message(FATAL_ERROR "alps_target_link_pyalps requires an existing target")
  endif()
  if(NOT PYALPS_PYTHON_EXECUTABLE)
    set(PYALPS_PYTHON_EXECUTABLE "${Python_EXECUTABLE}")
  endif()
  if(NOT PYALPS_PYTHON_EXECUTABLE)
    message(FATAL_ERROR "alps_target_link_pyalps requires a Python interpreter")
  endif()
  execute_process(COMMAND "${PYALPS_PYTHON_EXECUTABLE}" -c
    "import importlib.util,pathlib; s=importlib.util.find_spec('pyalps'); print(pathlib.Path(next(iter(s.submodule_search_locations))).resolve() if s and s.submodule_search_locations else '')"
    OUTPUT_VARIABLE package OUTPUT_STRIP_TRAILING_WHITESPACE
    COMMAND_ERROR_IS_FATAL ANY)
  set(manifest "${package}/runtime.json")
  if(NOT EXISTS "${manifest}")
    if(IS_DIRECTORY "${package}/../pyalps.libs" OR IS_DIRECTORY "${package}/.dylibs")
      message(FATAL_ERROR "The repaired pyalps wheel has no runtime.json; rebuild it with the runtime manifest packaging step")
    endif()
    target_link_libraries("${target}" PRIVATE ALPS::alps)
    return()
  endif()
  file(READ "${manifest}" metadata)
  string(JSON schema GET "${metadata}" schema)
  string(JSON version GET "${metadata}" alps_version)
  string(JSON repaired GET "${metadata}" repaired)
  if(NOT schema EQUAL 1 OR NOT version STREQUAL ALPS_VERSION)
    message(FATAL_ERROR "The pyalps runtime manifest requires schema 1 and the matching ALPS SDK version (${ALPS_VERSION})")
  endif()
  # Windows import libraries retain stable DLL names. Python registers the
  # wheel's bin directory before loading extensions. Unrepaired Unix builds
  # likewise use the SDK dependency names, without a second link interface.
  if(WIN32 OR NOT repaired)
    target_link_libraries("${target}" PRIVATE ALPS::alps)
    return()
  endif()

  target_link_libraries("${target}" PRIVATE ALPS::headers Threads::Threads)
  string(JSON count LENGTH "${metadata}" libraries)
  if(count EQUAL 0)
    message(FATAL_ERROR "The repaired pyalps wheel contains no runtime libraries")
  endif()
  file(REAL_PATH "${package}/.." site_packages)
  set(runtime_paths "")
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON relative GET "${metadata}" libraries ${index} path)
    file(REAL_PATH "${package}/${relative}" library)
    cmake_path(IS_PREFIX site_packages "${library}" NORMALIZE within_package)
    if(NOT within_package OR NOT EXISTS "${library}")
      message(FATAL_ERROR "Missing or invalid pyalps runtime file: ${relative}")
    endif()
    target_link_libraries("${target}" PRIVATE "${library}")
    get_filename_component(directory "${library}" DIRECTORY)
    list(APPEND runtime_paths "${directory}")
    if(APPLE)
      string(JSON install_name GET "${metadata}" libraries ${index} install_name)
      get_filename_component(filename "${library}" NAME)
      add_custom_command(TARGET "${target}" POST_BUILD
        COMMAND "${CMAKE_INSTALL_NAME_TOOL}" -change "${install_name}"
          "@rpath/${filename}" "$<TARGET_FILE:${target}>" VERBATIM)
    endif()
  endforeach()
  list(REMOVE_DUPLICATES runtime_paths)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # DT_RPATH also resolves transitive dependencies such as libgfortran.
    target_link_options("${target}" PRIVATE "LINKER:--disable-new-dtags")
  endif()
  set_property(TARGET "${target}" APPEND PROPERTY BUILD_RPATH ${runtime_paths})
  set_property(TARGET "${target}" APPEND PROPERTY INSTALL_RPATH ${runtime_paths})
  message(STATUS "${target}: using the recorded pyalps wheel runtime")
endfunction()
