#!/usr/bin/env python

import sys
import pyalps
import worldlines

if (len(sys.argv) == 1):  # select all files
  files = pyalps.getResultFiles(dirname=".", pattern="*.out.run1.h5");

  for file in files:
    wl = worldlines.worldlines()
    wl.load(file);
    wl.save(file[0:-12] + ".worldlines.h5");

elif (len(sys.argv) == 2):  # input filename given
  file = sys.argv[1];
  
  wl = worldlines.worldlines()
  wl.load(file);
  wl.save(file[0:-12] + ".worldlines.h5");

elif (len(sys.argv) == 3):  # input and output filenames both given
  infile  = sys.argv[1];
  outfile = sys.argv[2];

  wl = worldlines.worldlines()
  wl.load(infile);
  wl.save(outfile);
