#!/opt/local/bin/python

import sys
import numpy
import scipy
import pyalps.hdf5

### Checking for system errors
if (len(sys.argv) != 2):
  print "\n";
  print "Warnung!!! Bitte geben Sie den folgenden Befehl ein."
  print "  converged.py <filename-of-measurements-in-hdf5-format>"
  print "\n"
  sys.exit(2)

### Loading
infile = sys.argv[1];
iar = pyalps.hdf5.iArchive(infile);

measurements_n = iar.read("/simulation/results/Density");
measurements_e = iar.read("/simulation/results/Energy Density")

converged_n = (measurements_n['mean']['error_convergence'] == 0)
converged_e = (measurements_e['mean']['error_convergence'] == 0)
converged   = (converged_n and converged_e)

n_count = measurements_n['count']

n_mean  = measurements_n['mean']['value']
n_error = measurements_n['mean']['error']
n_tau   = measurements_n['tau']['value']

e_mean  = measurements_e['mean']['value']
e_error = measurements_e['mean']['error']
e_tau   = measurements_e['tau']['value']

### Printing
print converged
print "Converged density: " + str(converged_n)
print "Converged energy: " + str(converged_e)
print "Count: " + str(n_count)
print "Density: " + str(n_mean) + " " + str(n_error) + " " + str(n_tau)
print "Energy: " + str(e_mean) + " " + str(e_error) + " " + str(e_tau)
