#!/opt/local/bin/python

import sys
import pyalps
import pyalps.hdf5
import worldlines

if (len(sys.argv) == 1):  # select all files
  files = pyalps.getResultFiles(dirname=".", pattern="*.out.run1.h5");

  for file in files:
    iar = pyalps.hdf5.iArchive(file);
    oar = pyalps.hdf5.oArchive(file[0:-3] + ".positions.h5");
    oar.write("/positions", iar.read("/simulation/positions"));

elif (len(sys.argv) == 2):  # input filename given
  file = sys.argv[1];
  
  iar = pyalps.hdf5.iArchive(file);
  oar = pyalps.hdf5.oArchive(file[0:-3] + ".positions.h5");
  oar.write("/positions", iar.read("/simulation/positions"));

elif (len(sys.argv) == 3):  # input and output filenames both given
  infile  = sys.argv[1];
  outfile = sys.argv[2];

  iar = pyalps.hdf5.iArchive(infile);
  oar = pyalps.hdf5.oArchive(outfile);
  oar.write("/positions", iar.read("/simulation/positions"));
